# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29d4fc70891ca03daf33c4aba254fdd34ca9392740bd58c92f207136f6551f6286e4d111a61c59af73c3be893327427c8487e09f42bf62905adde5b490d8ded2

test:
  secret_key_base: 6fcfd6e34558db4f81b88d1e3a6a57da1f348d421caaedd85564c46d790862d0170e74226e6b37b7ef9cc74002a42422d9b717b2ff94a0fc0626d216e6fe5d8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
